// Mozilla User Preferences

// DO NOT EDIT THIS FILE.
//
// If you make changes to this file while the application is running,
// the changes will be overwritten when the application exits.
//
// To change a preference value, you can either:
// - modify it via the UI (e.g. via about:config in the browser); or
// - set it within a user.js file in your profile.

user_pref("app.normandy.first_run", false);
user_pref("app.normandy.startupRolloutPrefs.network.cookie.cookieBehavior", 4);
user_pref("app.normandy.user_id", "20ab16ef-2bb8-4875-b354-510dc56c9944");
user_pref("app.update.lastUpdateTime.addon-background-update-timer", 1579041070);
user_pref("app.update.lastUpdateTime.blocklist-background-update-timer", 1579041190);
user_pref("app.update.lastUpdateTime.browser-cleanup-thumbnails", 1579041765);
user_pref("app.update.lastUpdateTime.recipe-client-addon-run", 1579040830);
user_pref("app.update.lastUpdateTime.search-engine-update-timer", 1579004437);
user_pref("app.update.lastUpdateTime.services-settings-poll-changes", 1579040950);
user_pref("app.update.lastUpdateTime.telemetry_modules_ping", 1579041430);
user_pref("app.update.lastUpdateTime.xpi-signature-verification", 1579041310);
user_pref("browser.bookmarks.restore_default_bookmarks", false);
user_pref("browser.cache.disk.amount_written", 123937);
user_pref("browser.cache.disk.capacity", 1048576);
user_pref("browser.cache.disk.filesystem_reported", 1);
user_pref("browser.contentblocking.category", "standard");
user_pref("browser.contentblocking.introCount", 5);
user_pref("browser.laterrun.bookkeeping.profileCreationTime", 1579004288);
user_pref("browser.laterrun.bookkeeping.sessionCount", 2);
user_pref("browser.laterrun.enabled", true);
user_pref("browser.migration.version", 81);
user_pref("browser.newtabpage.activity-stream.feeds.section.highlights", false);
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.rec.impressions", "{\"52087\":1579041773713,\"52092\":1579041773713,\"52094\":1579044700472}");
user_pref("browser.newtabpage.activity-stream.feeds.section.topstories.spoc.impressions", "{\"2188\":[1579041773712,1579041871442,1579042182424,1579042515004,1579042868692,1579042894726],\"2345\":[1579043025562,1579044700471]}");
user_pref("browser.newtabpage.activity-stream.impressionId", "{d274f5e3-8596-4848-b691-227e3a567bd7}");
user_pref("browser.newtabpage.activity-stream.improvesearch.topSiteSearchShortcuts.havePinned", "amazon");
user_pref("browser.newtabpage.activity-stream.prerender", false);
user_pref("browser.newtabpage.pinned", "[{\"url\":\"https://amazon.com\",\"label\":\"@amazon\",\"searchTopSite\":true}]");
user_pref("browser.newtabpage.storageVersion", 1);
user_pref("browser.pageActions.persistedActions", "{\"version\":1,\"ids\":[\"bookmark\",\"pinTab\",\"bookmarkSeparator\",\"copyURL\",\"emailLink\",\"addSearchEngine\",\"sendToDevice\",\"pocket\",\"screenshots_mozilla_org\"],\"idsInUrlbar\":[\"pocket\",\"bookmark\"]}");
user_pref("browser.pagethumbnails.storage_version", 3);
user_pref("browser.safebrowsing.provider.google4.lastupdatetime", "1579043577192");
user_pref("browser.safebrowsing.provider.google4.nextupdatetime", "1579045374192");
user_pref("browser.safebrowsing.provider.mozilla.lastupdatetime", "1579041541045");
user_pref("browser.safebrowsing.provider.mozilla.nextupdatetime", "1579045141045");
user_pref("browser.search.region", "US");
user_pref("browser.shell.mostRecentDateSetAsDefault", "1579041741");
user_pref("browser.slowStartup.averageTime", 11155);
user_pref("browser.slowStartup.samples", 2);
user_pref("browser.startup.homepage_override.buildID", "20190718161435");
user_pref("browser.startup.homepage_override.mstone", "68.0.1");
user_pref("browser.startup.lastColdStartupCheck", 1579041738);
user_pref("browser.uiCustomization.state", "{\"placements\":{\"widget-overflow-fixed-list\":[],\"nav-bar\":[\"back-button\",\"forward-button\",\"stop-reload-button\",\"home-button\",\"customizableui-special-spring1\",\"urlbar-container\",\"customizableui-special-spring2\",\"downloads-button\",\"library-button\",\"sidebar-button\",\"fxa-toolbar-menu-button\"],\"toolbar-menubar\":[\"menubar-items\"],\"TabsToolbar\":[\"tabbrowser-tabs\",\"new-tab-button\",\"alltabs-button\"],\"PersonalToolbar\":[\"personal-bookmarks\"]},\"seen\":[\"developer-button\"],\"dirtyAreaCache\":[\"nav-bar\",\"toolbar-menubar\",\"TabsToolbar\",\"PersonalToolbar\"],\"currentVersion\":16,\"newElementCount\":2}");
user_pref("browser.urlbar.placeholderName", "Google");
user_pref("datareporting.policy.dataSubmissionPolicyAcceptedVersion", 2);
user_pref("datareporting.policy.dataSubmissionPolicyNotifiedTime", "1579004293790");
user_pref("devtools.onboarding.telemetry.logged", true);
user_pref("distribution.canonical.bookmarksProcessed", true);
user_pref("distribution.iniFile.exists.appversion", "68.0.1");
user_pref("distribution.iniFile.exists.value", true);
user_pref("dom.push.userAgentID", "69988c22f6a14eadab01a8d98d845cac");
user_pref("extensions.activeThemeID", "default-theme@mozilla.org");
user_pref("extensions.blocklist.lastModified", "Tue, 14 Jan 2020 22:08:07 GMT");
user_pref("extensions.blocklist.pingCountTotal", 2);
user_pref("extensions.blocklist.pingCountVersion", 2);
user_pref("extensions.databaseSchema", 31);
user_pref("extensions.getAddons.cache.lastUpdate", 1579041070);
user_pref("extensions.getAddons.databaseSchema", 5);
user_pref("extensions.incognito.migrated", true);
user_pref("extensions.lastAppBuildId", "20190718161435");
user_pref("extensions.lastAppVersion", "68.0.1");
user_pref("extensions.lastPlatformVersion", "68.0.1");
user_pref("extensions.pendingOperations", false);
user_pref("extensions.systemAddonSet", "{\"schema\":1,\"directory\":\"{a6ece0c8-9d19-4400-a0a6-5b7f45eb16f0}\",\"addons\":{\"webcompat@mozilla.org\":{\"version\":\"6.1.0\"}}}");
user_pref("extensions.webcompat.perform_injections", true);
user_pref("extensions.webcompat.perform_ua_overrides", true);
user_pref("extensions.webextensions.uuids", "{\"formautofill@mozilla.org\":\"17329a02-4c0e-4482-ba07-25ba29c5d666\",\"fxmonitor@mozilla.org\":\"0f6a2a82-9396-4e9b-8a7c-6ffd6e098076\",\"screenshots@mozilla.org\":\"df15e2ac-c9ec-432f-bcf6-611b9c5ccbc3\",\"webcompat-reporter@mozilla.org\":\"9ed2249b-fdf6-43da-8e1d-390ca51bb804\",\"webcompat@mozilla.org\":\"bba60494-47be-4efb-b784-58dda66d919e\",\"default-theme@mozilla.org\":\"e4fb4a53-cf4d-4700-bd6f-792b155e9d12\",\"google@search.mozilla.org\":\"a915b501-0d86-4bcd-bfc0-489272e2f26a\",\"amazondotcom@search.mozilla.org\":\"1a4f2ccc-234f-4ec5-ab14-f5c5ac71a1ff\",\"bing@search.mozilla.org\":\"c4d35609-5842-4ed1-9488-f64537257bdc\",\"ddg@search.mozilla.org\":\"5d5cb2ae-9082-4d91-a7d1-d1a2d9fcb3c8\",\"ebay@search.mozilla.org\":\"a5db9d88-66f6-4612-ad8c-f72043f310d4\",\"twitter@search.mozilla.org\":\"4bd3e874-15f7-4707-a9f9-dba88f9a8100\",\"wikipedia@search.mozilla.org\":\"d3ee664a-0a08-42db-942d-bca75ca1fe95\"}");
user_pref("font.internaluseonly.changed", true);
user_pref("idle.lastDailyNotification", 1579043735);
user_pref("media.gmp-manager.buildID", "20190718161435");
user_pref("media.gmp-manager.lastCheck", 1579004327);
user_pref("media.gmp.storage.version.observed", 1);
user_pref("network.predictor.cleaned-up", true);
user_pref("pdfjs.enabledCache.state", true);
user_pref("pdfjs.migrationVersion", 2);
user_pref("pdfjs.previousHandler.alwaysAskBeforeHandling", true);
user_pref("pdfjs.previousHandler.preferredAction", 4);
user_pref("permissions.eventTelemetry.salt", "{3b2b1184-a9c6-4458-809c-70e9efc1b114}");
user_pref("places.database.lastMaintenance", 1579043735);
user_pref("places.history.expiration.transient_current_max_pages", 112348);
user_pref("plugin.disable_full_page_plugin_for_types", "application/pdf");
user_pref("privacy.sanitize.pending", "[{\"id\":\"newtab-container\",\"itemsToClear\":[],\"options\":{}}]");
user_pref("security.sandbox.content.tempDirSuffix", "e041b493-0599-4492-a97c-b167dc9c7c5e");
user_pref("security.sandbox.plugin.tempDirSuffix", "db45ca0b-58a8-4bad-96c2-2846ee532d1a");
user_pref("services.blocklist.pinning.checked", 1579041202);
user_pref("services.settings.clock_skew_seconds", -129);
user_pref("services.settings.last_etag", "\"1579039687654\"");
user_pref("services.settings.last_update_seconds", 1579041169);
user_pref("services.settings.main.cfr-fxa.last_check", 1579041202);
user_pref("services.settings.main.cfr.last_check", 1579041202);
user_pref("services.settings.main.fxmonitor-breaches.last_check", 1579041202);
user_pref("services.settings.main.hijack-blocklists.last_check", 1579041202);
user_pref("services.settings.main.language-dictionaries.last_check", 1579041202);
user_pref("services.settings.main.normandy-recipes.last_check", 1579041202);
user_pref("services.settings.main.sites-classification.last_check", 1579041202);
user_pref("services.settings.main.tippytop.last_check", 1579041202);
user_pref("services.settings.main.url-classifier-skip-urls.last_check", 1579041202);
user_pref("services.settings.security.onecrl.checked", 1579041202);
user_pref("signon.importedFromSqlite", true);
user_pref("storage.vacuum.last.index", 0);
user_pref("storage.vacuum.last.places.sqlite", 1579043735);
user_pref("toolkit.startup.last_success", 1579041729);
user_pref("toolkit.telemetry.cachedClientID", "fedc4aca-2f12-476a-a8e0-b34e19b60e2e");
user_pref("toolkit.telemetry.previousBuildID", "20190718161435");
user_pref("toolkit.telemetry.reportingpolicy.firstRun", false);
user_pref("trailhead.firstrun.didSeeAboutWelcome", true);
